#!/bin/bash


################## Installing SRATools for Ubuntu64, adding /bin to the Path
mkdir SraTools
cd SraTools
wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.9.1-1/sratoolkit.2.9.1-1-ubuntu64.tar.gz
tar -xzvf sratoolkit.2.9.1-1-ubuntu64.tar.gz
export PATH=$PWD/sratoolkit.2.9.1-1-centos_linux64/bin/:${PATH}


cd ..
mkdir sraDir
vdb-config -i
prefetch SRR7555666
prefetch SRR7555667



########################## Converting all sra files in sraDir fol
mkdir fastq
for sraFile in sraDir/sra/*.sra; do
 echo "Extracting fastq from "${sraFile}
 fastq-dump \
    --origfmt \
    --gzip \
    --outdir fastq \
    ${sraFile}
done
########################## Downloading FASTQC toolkit into FASTQC
mkdir FASTQC
cd FASTQC
wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.7.zip
unzip fastqc_v0.11.7.zip
chmod +x FastQC/fastqc
export PATH=$PWD/FastQC:${PATH}
############################  Running Quality check using Fastcq function and 20 cores
cd ..
mkdir fastqcfiles
fastqc -o fastqcfiles/ fastq/*fastq.gz -t 20
############################ REference data downlod from ensemble
cd ..
mkdir referencedata/fasta
cd referencedata/fasta
wget ftp://ftp.ensembl.org/pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz
gunzip Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa.gz

########################### GFT file of the reference data

cd ..
mkdir annotations
cd annotations
wget ftp://ftp.ensembl.org/pub/release-98/gtf/homo_sapiens/Homo_sapiens.GRCh38.98.gtf.gz
gunzip Homo_sapiens.GRCh38.98.gtf.gz
########################## Download and intall STAR
cd ../..
mkdir STAR
cd STAR
wget https://github.com/alexdobin/STAR/archive/2.7.3a.tar.gz
tar -xzf 2.7.3a.tar.gz
cd STAR-2.7.3a/bin/Linux_x86_64 ##For ubuntu
chmod +x ./STAR #making it excutable
PATH=../Linux_x86_64/:$PATH
########################## Creating gene indeces with STAR
cd ..
mkdir STARindex/GenomeDir
STAR --runThreadN 20 --runMode genomeGenerate --genomeFastaFiles ../referenceData/fasta/Homo_sapiens.GRCh38.dna_rm.primary_assembly.fa --sjdbGTFfile ../referenceData/annotations/Homo_sapiens.GRCh38.98.gtf --sjdbOverhang 99
######
